web/Changelog.md
web/src/Pages/Login/SignUp/index.js

https://ceg4912capstone.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=CC&modal=detail&selectedIssue=CC-51

Added Firebase Sign Up

---

web/src/Pages/Login/SignUp/index.js

Fixed Birth Date Calendar

---

.gitignore
backend/package-lock.json
backend/package.json
backend/server.js
database/createDB.sql
database/queryDB.sql
web/src/Pages/Login/SignUp/index.js

backend connection to db

---

database/createDB.sql
flaskBackend/server.py

implemented request for sensor data

---

flaskBackend/server.py
web/src/Pages/DeveloperPages/Sensor/Charts/SensorPressure.js
web/src/Pages/DeveloperPages/Sensor/Charts/SensorTemperature.js
web/src/Pages/DeveloperPages/Sensor/Charts/firebase/SensorPressure.js
web/src/Pages/DeveloperPages/Sensor/Charts/firebase/SensorTemperature.js

Refactored UI for postgres

---

web/src/Pages/DeveloperPages/Sensor/Charts/SensorPressure.js
web/src/Pages/DeveloperPages/Sensor/Charts/SensorTemperature.js

Cors Policy

---

web/src/Pages/DeveloperPages/Sensor/Charts/SensorPressure.js
web/src/Pages/DeveloperPages/Sensor/Charts/SensorTemperature.js

Cors Policy2

---

web/README.md
web/package-lock.json
web/package.json

updated readme and dependencies

mdiep/updated README and dependencies

---

package-lock.json
web/README.md
web/src/Layout/AppMain/PageTitle.js
web/src/Layout/AppMain/PageTitle/Variation2.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/Alert.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/Charts/SensorHumidity.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/Charts/SensorPressure.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/Charts/SensorTemperature.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/index.js
web/src/Pages/CaregiverPages/UsersSchedulePage/index.js

Foundational layer of UI Components for Caregiver View.

mdiep/caregiverView: Added UI Components for Caregiver View

---

web/README.md
web/package-lock.json
web/src/Pages/PatientPages/ContactDoctor/Alert.js
web/src/Pages/PatientPages/ContactDoctor/index.js
web/src/Pages/PatientPages/Dashboard/Alert.js
web/src/Pages/PatientPages/Dashboard/index.js
web/src/Pages/PatientPages/Pills/Alert.js
web/src/Pages/PatientPages/Pills/index.js
web/src/Pages/PatientPages/Schedule/index.js

Contains foundational components and layouts for Patient View Pages.

Mdiep/patientView: Foundational Components

---

web/src/Layout/AppNav/NavItems.js
web/src/Layout/AppNav/VerticalNavWrapper.js
web/src/Layout/AppSidebar/index.js

-   [ ] Ran Code locally
-   [ ] Updated any appropriate README files
-   [ ] Checked by at least 1 other person (please with comments if applicable)
-   [ ] Fixed any issues, or added new issues if not applicable

Applied fix to the Side Nav Button always being highlighted

---

web/src/Layout/AppNav/NavItems.js
web/src/Layout/AppNav/VerticalNavWrapper.js

-   [ y] Ran Code locally
-   [y ] Updated any appropriate README files
-   [ na] Create a simple testbench (e.g a __main__ function)
-   [ na] Added Unit Testing 
-   [y ] Checked by at least 1 other person (please with comments if applicable)
-   [ y] Fixed any issues, or added new issues if not applicable

Adapted fix to sidenav to patient and caregiver view

---

web/src/Pages/PatientPages/ContactDoctor/index.js

-   [ ] Updated any appropriate README files
-   [ ] Checked by at least 1 other person (please with comments if applicable)
-   [ ] Fixed any issues, or added new issues if not applicable

ContactDoctor page

---

web/src/Layout/AppHeader/Components/PatientDropDown.js
web/src/Layout/AppHeader/index.js
web/src/Layout/AppMain/PageTitle.js
web/src/Layout/AppMain/index.js
web/src/Layout/AppNav/VerticalNavWrapper.js

mdiep/refactorAppLayout: Applied layout change, fixed developer view, and added patient box component

---

web/src/Layout/AppNav/NavItems.js
web/src/Layout/AppNav/VerticalNavWrapper.js

mdiep/refactorAppLayout: Changed icons on side nav, and fixed minor bugs"

---

web/src/Layout/AppMain/PageTitle.js
web/src/Layout/AppMain/index.js
web/src/Pages/CaregiverPages/MessageUsersPage/index.js
web/src/Pages/CaregiverPages/UsersAnalysisPage/index.js
web/src/Pages/CaregiverPages/UsersSchedulePage/index.js
web/src/Pages/DeveloperPages/Sensor/index.js
web/src/Pages/PatientPages/ContactDoctor/index.js
web/src/Pages/PatientPages/Dashboard/index.js
web/src/Pages/PatientPages/Pills/index.js
web/src/Pages/PatientPages/Schedule/index.js

mdiep/keepPageTitleFixed: Applied a fix to keep the Page Title Fixed.

---

web/src/Layout/AppHeader/Components/UserBox.js
web/src/Layout/AppHeader/index.js
web/src/Layout/AppMain/index.js
web/src/Pages/Main/index.js
web/src/Pages/SettingsPage.js

mdiep/functionalityOfUserDropDownBox: Added functionalities to user drop down box and added settings page.

---

flaskBackend/server.py
web/src/Pages/Login/SignUp/index.js

-   [ ] Fixed any issues, or added new issues if not applicable

applied userid to handle login

---

database/createDB.sql
database/queryDB.sql
flaskBackend/server.py
web/src/Layout/AppMain/index.js
web/src/Pages/Login/SignUp/index.js

Added caregiverId to DB table and UI routing

---

database/createDB.sql
web/src/Pages/Login/SignUp/index.js

converted doctorId to int

---

flaskBackend/server.py

-   [ ] Updated any appropriate README files
-   [x] Added Unit Testing 

added function to get patients

---

web/src/Pages/CaregiverPages/MessageUsersPage/index.js
web/src/Pages/PatientPages/ContactDoctor/index.js
web/src/components/MessagesComponent.js

applied proper routing for sending/receiving messages

---

flaskBackend/server.py

Added flaskbackend for messaging

---

flaskBackend/alarm.py

-   [ ] Updated any appropriate README files
-   [ ] Fixed any issues, or added new issues if not applicable

converted from micros to milis
